learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
    
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from .import views

app_name = 'learning_logs'
urlpatterns = [
	#HOME PAGE
	#this has three parameters the first, how it appears in the url
	#the sencod is the name of the function in the views file
	#the third is a a name we can used to link to the page insted of using the whole url

	path('', views.index, name='index'),
	path('topics/', views.topics, name='topics'),
	path('topics/<int:topic_id>/', views.topic, name='topic'),
	#we need to used the id of the topic for the individual topic template
	path('new_topic/', views.new_topic, name='new_topic'),
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
	]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	#Include a default auth urls.
	path('', include('django.contrib.auth.urls')),
	#Registration Page:
	path('register/', views.register, name='register'),
	
]

	

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic (models.Model):
	"""A topic the user is learning about."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	"""
	#create a foreign Key relationship to the user model.
	   #if the user is deleted all topics associated with that user will be delated as well.
	   #with the Foreing key relation ship and the code in the view model, the topics will be from now on associated with the user that create it
	   #topics created before that did´t hava that connection so there is a way to associate them to an user as well as the super user. look for inf page 594
	   #when we migrate, will tell python to manage to modify the database structure, but we can delete all using 'python manage.py flush'
	   #when a user is delated all the structure and inf associated will be delated as well."""
	def __str__(self):
		"""Return a string representation of the model"""
		return self.text 
	
class Entry(models.Model):
	"""Something specific learned about a topic."""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)#ForeingKey is a data base term, conects each entry to an specific term.
	text = models.TextField()                                 #on_deleta=models.Cascada, when a topic is delated all entries as well 
	date_added = models.DateTimeField(auto_now_add= True)
	
	class Meta:
		verbose_name_plural = 'entries'
		
	def __str__(self):
		"""Return a string representation of the model."""
		return f"{self.text[:50]}..."
 
 

learning_logs/forms.py
#A form to submit inf. this case to submit a new topic 
from django import forms #
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic #The model we are gonna work with
		fields = ['text']#only text
		labels = {'text': ''}# to tell django no to add labels
		
		
class EntryForm(forms.ModelForm):
	class Meta:#A meta classs inside another class tell the class how to behave
		model= Entry
		fields= {'text'}# cuadro de texto
		labels= {'text': ' '}#sin etiquetas
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}#le da formato al cuadro de texto

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required # For restricting 
from django.http import Http404

#Create your views here.
"""
#Nota: Templates are store in a folder called learning_logs inside a templatefolder
#inside the learning_logs principal folder."""

def index(request):
	"""The home page for Learning Log."""
	return render(request, 'learning_logs/index.html') 

@login_required 
#its a decorator, restrict access to the requested Page if the user is not authenticated.
#has to add a the following line: LOGIN_URL = 'users:login' to project settings at the end
def topics(request):
	"""Show all topics"""
	topics= Topic.objects.filter(owner=request.user).order_by('date_added')
	"""
		# will filter only the topics associeted with that user.
		#this part is when we are conecting topics with users 
		#topics = Topic.objects.order_by('date_added')#get the Topics from de data base
		"""
	context = {'topics': topics}#create a list with the topics will be sent to the template
	return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id): #topic_id saves de parameter the url is sending
	"""Show a single topic an all its entries."""
	topic = Topic.objects.get(id=topic_id) #we use get to retrive the topic, base in its id
	#MAKE SURE THE TOPIC BELONGS TO THE CURRENT USER:
	check_topic_owner(request, topic)
	#if topic.owner != request.user:
	#	raise Http404 
	"""
	#even though the user is not authenticated or is a diferent user, it is still posible to see pages just by coping the Url to
	#the broswer, this code avoids that."""
	entries = topic.entry_set.order_by('-date_added') 
	"""
	#the - display the most recent entries first
    #this last too lines are called queries, because they query the data base for specif inf.	"""
	context = {'topic': topic, 'entries': entries}#save the data in a dic, to be send to the topic template
	return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
	"""Add a new topic"""
	if request.method != 'POST': #whether the request is a GET or POST
		#No data submitted; create a blanck form. b
		form= TopicForm()
	else:
		#POST data submitted, process data.
		form = TopicForm(data=request.POST)#
		if form.is_valid():
			#form.save()
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			"""
			#before adding these 3 last lines of code, an error ocurred, 'IntegrityError along with NOT NULL
            #constraint failed: learning_logs_topic.owner_id.' this was because the topic was not associetted correctly with a its user.
            #To correctly associate a user with its topics, first neeed to add the Forei gnKey method at topic model, so m  nodels can be conected,
            #then in the view funtion, using the las 3 lines of codes you associate the topic with the correct user. """
			return redirect('learning_logs:topics')#Redirects the user to a view funtion
			 
	#DISPLAY A BLANK OR INDIVIDUAL FORM
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)
	"""
	#GET AND POST: GET is used to get data from the server, POST when user needs to submitt inf through a form.
	#Initially when the page is requested the broswer will send a GET request because somethimes user is asking for a 
	#form filled of inf. from the server, in this case it´s not necesary just need a empty form to fill and then submitt
	#inf, using the POST request to send data to the server"""
	
@login_required  
def new_entry(request, topic_id):
	"""Add a new entry for a particular topic"""
	topic= Topic.objects.get(id=topic_id)
	check_topic_owner(request, topic)
	"""
	#if topic.owner != request.user:
		#raise Http404
	    #even though the user is not authenticated or is a diferent user, it is still posible to see pages just by coping the Url to
		#the broswer, this code avoids that."""
	if request.method != 'POST':
		#No data submitted; create a blank form.
		form = EntryForm()
	else:
		#POST data submitted; process data.
		form = EntryForm(data=request.POST)#creating an instance of EntryForm
		if form.is_valid():# validating data
			new_entry = form.save(commit=False)#save the form with the new data in an object, and tells djangon not to save to database yet
			new_entry.topic= topic #relate to the topic
			new_entry.save()# save to data base
			return redirect('learning_logs:topic', topic_id=topic_id)
	
	#Display a blank or invalid form.
	context = {'topic': topic, 'form': form}#this part will ejecute with a black form of invalid data form 
	return render (request, 'learning_logs/new_entry.html', context)
	
@login_required
def edit_entry(request, entry_id):
	"""Edit an existing entry"""
	entry = Entry.objects.get(id=entry_id)#get the entry using the entry_id send by the url
	topic =entry.topic #get the topic that is alredy related to entry
	check_topic_owner(request, topic)
	if request.method != 'POST': #the user is requesting a form fill with the entry inf, so can be editted and saved
		#Initial reques; pre-fill form with the current entry.
		form = EntryForm(instance=entry)
	else:
		#Post data submitted, proces data.
		#the entry has been editten and user request to update the entry
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():#validate the edited entry
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)#redirect to topic view
		
	context = {'entry': entry, 'topic':topic, 'form':form}
	return render(request, 'learning_logs/edit_entry.html', context)
	
	

def check_topic_owner(request, topic):
	""""check if the topic owner maches the current user"""
	if topic.owner != request.user:
		raise Http404
	

	
	
	
	
	
	
	
	
	
	
	

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}<!-- load the collection of templates available on django-bootstrap4  -->

<!doctype html><!-- declared as HTML document  -->
<html lang="en"> <!-- written in english -->
<head><!-- the head tells the browser what it needs to know to display the page correctly -->
 <meta charset="utf-8">
 <meta name= "viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <title> Learning Log</title><!-- it will be display in the browser´s title bar -->
	
 {% bootstrap_css %}<!-- we use one of the django-bootstrap4´s custom template tags, which tells django to include all the boostrap style files.  -->
 {% bootstrap_javascript jquery='full' %}<!-- enables all the interactive behavior you might use on the page -->
	

</head> <!--closing head tag  -->

<body><!-- openning body tag, conteins the content users will see on a page.-->
	
 <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border"> <!-- nav element indicates the page´s navigation links section -->
		<!-- Everything is style acording bootstrap rules by selectors: navbar, navbar-expand-md, they tell which elements on a page a certain style rules applies to -->
		<!-- navbar-light and bg-light selectors style the navigation bar with a light-themed backgroud -->
		<!-- mb in mb-4 is short for margin-bottom, makes appear a little space between the navigation bar and the rest of the page -->
		<!-- border selector provides a thin border around the light background.-->
  <a class="navbar-brand" href="{% url 'learning_logs:index'%}"> Learning_log </a><!-- we set project´s name to appear at the far left of the navigation bar, is a link to home page -->
		<!-- it will appear on every page in the project -->
		<!-- the navbar-brand selector styles this link so it stands out -->
		
	<!-- Botton that appears if the browser is to narrow, to display the whole bar -->
  <button class ="navbat-toggler" type="button" data-toggle="collapse"
    data-target="#navbarCollapse" aria-controls="navbarCollapse"
	aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span></button>
		<!-- the collapse reference causes the navigation bar to collpase whe the user shrinks the browser window or when the site is display on a mobile device. -->
		
		<!-- This is the begining of the navigation bar that will collapse  -->
  <div class="collapse navbar-collapse" id="navbarCollapse"><!-- div is short for division, a div class styles everthing inside it -->
	  <!--this is the part that will be collapsed -->
   <ul class="navbar-nav mr-auto"><!--bootstrap defines every navigation element as an item  -->
	<li class="nav-item">
	<a class="nav-link" href="{% url 'learning_logs:topics' %}"> Topics </a></li>
   </ul>
	 
   <ul class="navbar-nav ml-auto"><!-- another item, you can have many as you want, ml-auto is short for margin-left-automatic creates a margin 
	   that pushes the element to the left of the screen -->
    {% if user.is_authenticated %}
	 <li class="nav-item">
	  <span class="navbar-text">Hello {{ user.username }}. </span><!-- span styles pieces of text, or elements of a page -->
	 </li>
	 <li class="nav-item">
	  <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
	 </li>
	{% else %}
	 <li class="nav-item">
	  <a class="nav-link" href="{% url 'users:register' %}"> Register</a>
	 </li>
	 <li class="nav-item">
	   <a class="nav-link" href="{% url 'users:login' %}"> Login </a></li>
	{% endif %}
   </ul>
  </div>
 </nav>
   
<!--Main Part of the Page  -->
 <main role="main" class="container"><!--here we assing the bootstrap selector conteiner a simple way to group elements on a page -->
  <div class="pb-2 mb-2 border-bottom"><!-- contains a page header, styles with a bottom margin, -->
   {% block page_header %}{% endblock page_header %}<!-- we are gonna put the tittle of the page here -->
  </div>
  <div>
   {% block content %}{% endblock content %}
  </div>
 </main>
</body>
</html>
	 
	 
	 
	 

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_head %}
 <h3> <a href="{% url 'learning_logs:topic' topic.id %">{{ topic }}</a></h3>

{% endblock page_head %}

{% block content %}
<!-- -->
 <h4> Edit entry: </h4>
<!--looks like initially the the broswer request is by default 'GET', this way the form wiht the entry will apear initially-->
 <form method='post' action="{% url 'learning_logs:edit_entry' entry.id %}" class="form" ><!-- with the entry edited, we redirect to the new_entry view with the request 'POST'-->
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
   <button name="submit" class="btn btn-primary">Save changes</button> 
  {% endbuttons %} 
 </form>
 
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}<!--This is the main part of the page, here goes the tittle, and itroducction -->
<img src="challenger.jpg" class="img-fluid" alt="...">

 <div class="jumbotron"><!--  its a div element with styling directives, its like a box, where we can put inf. inside are three elements-->
   <h1 class="display-3"> Track your learning.  </h1><!-- h1 class is a first-level header, display-3 selector adds a thinner an taller look at this header -->
   
    <p class="lead"> Make your own Learning_log, and keep a list of the topics 
		you´re learning about. Whenever you learn somethin new about a topic, make an
		entry summarizing what you´ve learned.
    </p> <!-- we include a large messange that provides more inf -->

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button"> Register &raquo;</a><!-- this is a button -->
       <!-- the &raquo are the 2 angle brackets (>>) -->
 </div>

{% endblock page_header %}
     
 

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3> <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3> 
{% endblock page_header %}
  
{% block content %}
 <!-- titulo con link a la pagina del tema actual, se usa topic.id para identificar ese tema, varia-->
 <h4> Add a new Entry: </h4> 
	 
 <form method='post' action= "{% url 'learning_logs:new_entry' topic.id %}" class="form" ><!-- redirecciona la informacion al la funcion view -->
  <!-- como POST request-->
  {% csrf_token %}<!-- segurida ante ataques en el trafico de la inf-->
  {% bootstrap_form form %}
  <!--{{ form.as_p}}  muestra el formulario -->
  {% buttons %}
   <button name="submit" class="btn btn-primary"> Add Entry</button><!-- boton-->
  {% endbuttons %}
  
  
 </form>

{% endblock content %}
   
<!-- -->

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}<!-- inherits from base template-->
{% load bootstrap4 %}

{% block page_header %}
 <h3> Add a new topic </h3>
{% endblock page_header %}


{% block content %}


 <form method='post' action= "{% url 'learning_logs:new_topic' %}" class="form" ><!--tells the brosewer where to send the data
	 send it back to the view funtion as a POST request -->
  {% csrf_token %}<!-- for security against cross-site request forgery attack-->
  {% bootstrap_form form %}
  <!-- {{ form.as_p}}shows the form-->
  
  {% buttons %}
   <button name="submit" class="btn btn-primary"> Add Topic</button><!--submit button -->
  {% endbuttons %}
  
  
 </form>
{% endblock content %}
<!-- -->

learning_logs/templates/learning_logs/topic.html
 <!-- Topic Template shows all the entries related with a single Topic -->
{% extends 'learning_logs/base.html' %} <!-- inherites from base template  -->
 <!-- Page for a single topic and its entries -->
{% block page_header %}
 <h3> {{ topic }}</h3>
{% endblock page_header %}

{% block content %}
<!-- -->
 <!-- <p>Topic: {{ topic }} </p>  Shows the title, its a variable -->
 
 <!-- <p>Entries: </p> -->
 <h5>
  <a href="{% url 'learning_logs:new_entry' topic.id %}"> Add new entry </a>
 </h5>
  
  
  {% for entry in entries %}
   <div class="card mb-3"><!--insted of a unorder list, we create a div class with a selector card, it has two nested elements-->
	<h4 class="card-header"><!-- it´s a card header h4 element, this one holds the timestamp an link to edit entry-->
     {{ entry.date_added|date:'M d, Y H:i' }}
     <small><a href="{% url 'learning_logs:edit_entry' entry.id%}"> Edit entry</a></small><!-- small tag makes it look smaller tan the timestamp -->
    </h4>
   
    <div class="card-body"> <!--it´s a dive qith the selector card-body, places the text of the entry in a simple box on the card -->
     {{ entry.text|linebreaks }}
     <!-- the caracter: | is a template filter to give format -->
    </div>
   </div>

  {% empty %}
   <p> There are no entries for this topic yet.</p>
  {% endfor %}
 
{% endblock content %}

   

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}<!--inherites from base template-->

{% block page_header %}
 <h1> Topics </h1>
{% endblock page_header %}


{% block content %}

 <!-- <p> Topics  </p> Tittle-->
  
 <ul><!-- bulleted list, an unorganized list -->
  {% for topic in topics %}<!--for loop, loops through every element in topics -->
   <li> <h4>
	 <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }}</a> <!-- URL template tag-->
   </h4></li>
   <!--prints, double braces indicates to django we are using template variables -->
  {% empty %}<!-- if the list is empty -->
   <li><h3>No topics have been added yet.</h3> </li>
  {% endfor %}<!--enf for loop -->
 </ul><!--end bulleted list  -->
 
 <h3><a href="{% url 'learning_logs:new_topic' %}"> Add a new topic </a> </h3><!--link for a new topic -->
{% endblock content %}